---
- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755 force=no

- name: Set hostname
  command: hostname {{sge_server_name}}

# Manage the /etc/hosts file
- name: Edit /etc/hosts file
  shell: |
    for i in `seq 1 {{max_number_of_nodes}}`; do
      item="{{vnode_prefix}}${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item}.localdomain" ${item} >> /etc/hosts;
    done

# SGE configuration Specific tasks
# specific tasks for RedHat
- block:
  - name: Copy 'is_cluster_ready' file
    copy: dest={{SGE_ROOT}}/my_configuration.conf src=centos7/my_configuration.conf mode=0666 force=no
    when: ansible_distribution_major_version|int == 7

  # specific tasks for Centos 6
  - name: qmaster installation (CentOS)
    action: shell cd {{SGE_ROOT}}; ./install_qmaster -auto ./my_configuration.conf creates={{SGE_ROOT}}/default/common/cluster_name
  when: ansible_os_family == "RedHat"

- name: add the frontend as submission host
  action: shell bash -lc 'qconf -as {{sge_server_name}}'
  ignore_errors: yes
#- command: qconf -as {{sge_server_name}}

- name: Create the nodes config files
  template: dest=/tmp/{{vnode_prefix}}{{item}}.def src=node.def
  with_sequence: start=1 end={{max_number_of_nodes}}

#- shell: qconf -se {{vnode_prefix}}{{item}}.localdomain || qconf -Ae /tmp/{{vnode_prefix}}{{item}}.def
#  with_sequence: start=1 end={{max_number_of_nodes}}
- name: add execution hosts
  action: shell bash -lc 'qconf -se {{vnode_prefix}}{{item}}.localdomain || qconf -Ae "/tmp/{{vnode_prefix}}{{item}}.def"'
  with_sequence: start=1 end={{max_number_of_nodes}}
  ignore_errors: yes

#- shell: qconf -ah {{vnode_prefix}}{{item}}.localdomain
#  with_sequence: start=1 end={{max_number_of_nodes}}
- name: add execution hosts
  action: shell bash -lc 'qconf -ah {{vnode_prefix}}{{item}}.localdomain'
  with_sequence: start=1 end={{max_number_of_nodes}}
  ignore_errors: yes

- name: Copy 'all_q.conf' file
  copy: dest=/tmp/all.q src=all_q.conf mode=0644 force=no

- copy:
    content: |
       group_name @allhosts
       hostlist {% for number in range(1, max_number_of_nodes|int + 1) %} {{vnode_prefix}}{{number}}.localdomain {% endfor %}
    dest: /tmp/allhosts.hgrp

#- shell: qconf -shgrp @allhosts || qconf -Ahgrp /tmp/allhosts.hgrp
- name: add hosts to the default queue
  action: shell bash -lc ' qconf -shgrp @allhosts || qconf -Ahgrp "/tmp/allhosts.hgrp"'
  ignore_errors: yes

#- shell: qconf -sq all.q || qconf -Aq /tmp/all.q
- name: create default queue
  action: shell bash -lc 'qconf -sq all.q || qconf -Aq /tmp/all.q'
  ignore_errors: yes
