---
- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755 force=no

- name: Set hostname
  command: hostname {{sge_server_name}}

# Manage the /etc/hosts file
- name: Edit /etc/hosts file
  shell: |
    for i in `seq 1 {{max_number_of_nodes}}`; do
      item="{{vnode_prefix}}${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item} ${item}.localdomain" >> /etc/hosts;
    done

# SGE configuration Specific tasks
- command: qconf -as {{sge_server_name}}

- name: Create the nodes config files
  template: dest=/tmp/{{vnode_prefix}}{{item}}.def src=node.def
  with_sequence: start=1 end={{max_number_of_nodes}}

- shell: qconf -se {{vnode_prefix}}{{item}} || qconf -Ae /tmp/{{vnode_prefix}}{{item}}.def
  with_sequence: start=1 end={{max_number_of_nodes}}

- shell: qconf -ah {{vnode_prefix}}{{item}}
  with_sequence: start=1 end={{max_number_of_nodes}}

- name: Copy 'all_q.conf' file
  copy: dest=/tmp/all.q src=all_q.conf mode=0644 force=no

- copy:
    content: |
       group_name @allhosts
       hostlist {% for number in range(1, max_number_of_nodes|int + 1) %} {{vnode_prefix}}{{number}} {% endfor %}
    dest: /tmp/allhosts.hgrp

- shell: qconf -shgrp @allhosts || qconf -Ahgrp /tmp/allhosts.hgrp
- shell: qconf -sq all.q || qconf -Aq /tmp/all.q
