---
- name: create epel.repo
  template: src=utils/templates/epel-es.repo dest=/etc/yum.repos.d/epel.repo

- name: Yum install SGE in REL system
  yum: name=gridengine,gridengine-execd,openssh-clients,gridengine-qmaster,gridengine-qmon

- name: Set RedHat facts
  set_fact:
    SGE_ROOT: /usr/share/gridengine
    EXEC_SERVICE: sge_execd

- name: Add SGE variables to /etc/sudoers
  lineinfile: 
    dest: /etc/sudoers
    line: 'Defaults    env_keep += "SGE_CELL SGE_ARCH SGE_EXECD_PORT SGE_QMASTER_PORT SGE_ROOT"'
    state: present
