---
- name: Wait until the file bootstrap on front is present before continuing
  wait_for:
    path: /opt/sge/default/common/bootstrap

- name: Copy service file
  copy: src=sge_execd.service dest=/etc/systemd/system/sge_execd.service
  notify: restart {{EXEC_SERVICE}}

